version: '3.4'

services:
  pm2:
    image: pm2
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "npm run start && echo 'PM2 Custom Server up and running' && sleep infinity"
    environment:
      NODE_ENV: production
