version: '3.4'

services:
  pm2:
    image: pm2
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001
      - 3002:3002
      - 3003:3003
      - 6665:6665
      - 6666:6666
      - 6667:6667
    command: ["npm", "run", "pm2"]
