version: '3.4'

services:
  pm2:
    image: pm2
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 9999:80
      - 6666
